#include "util_int.h"

#define BUILTIN_ARRAYS_IMPLEMENT(T_ELEM, ARRAY_NAME, ARRAY_PREFIX, SLICE_NAME, SLICE_PREFIX) \
    ARRAY_METHODS_IMPL_NAMED(ARRAY_PREFIX, T_ELEM, ARRAY_NAME)                      \
    SLICE_METHODS_IMPL_NAMED(SLICE_PREFIX, T_ELEM, SLICE_NAME)                      \
    SLICE_ARRAY_METHODS_IMPL_NAMED(ARRAY_PREFIX, T_ELEM, ARRAY_NAME, SLICE_NAME)    \

BUILTIN_ARRAYS_LIST(BUILTIN_ARRAYS_IMPLEMENT)

#undef BUILTIN_ARRAYS_IMPLEMENT
